# Generated by Django 4.1.4 on 2022-12-09 13:32

from django.db import migrations
from django.conf import settings


def change_default_site_name(apps, schema_editor):
    if settings.CURRENT_DOMAIN:
        Site = apps.get_model('sites', 'Site')
        site = Site.objects.get(name='example.com')
        site.name = settings.CURRENT_DOMAIN
        site.domain = settings.CURRENT_DOMAIN
        site.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_pet_id_petphoto'),
    ]

    operations = [
        migrations.RunPython(change_default_site_name)
    ]


from django.db import migrations

